unit TestUCompra;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, UCompra;

type
  // Test methods for class TCompra

  TestTCompra = class(TTestCase)
  strict private
    FCompra: TCompra;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestValorTotalComDesconto;
  end;

implementation

procedure TestTCompra.SetUp;
begin
  FCompra := TCompra.Create;
end;

procedure TestTCompra.TearDown;
begin
  FCompra.Free;
  FCompra := nil;
end;

procedure TestTCompra.TestValorTotalComDesconto;
var
  ReturnValue: Double;
begin
  //Sem Desconto
  FCompra.NomeProduto   := 'Pão';
  FCompra.Quantidade    := 10;
  FCompra.PrecoUnitario := 10.50;

  ReturnValue := FCompra.ValorTotalComDesconto;
  CheckEquals(105, ReturnValue, 'Valor Total Sem Desconto com erro!');

  //Com Desconto de 10%
  FCompra.NomeProduto   := 'Pão';
  FCompra.Quantidade    := 15;
  FCompra.PrecoUnitario := 10.50;

  ReturnValue := FCompra.ValorTotalComDesconto;
  CheckEquals(141.75, ReturnValue, 'Valor Total Com 10% Desconto com erro!');

  //Com Desconto de 25%
  FCompra.NomeProduto   := 'Pão';
  FCompra.Quantidade    := 55;
  FCompra.PrecoUnitario := 10.50;

  ReturnValue := FCompra.ValorTotalComDesconto;
  CheckEquals(433.125, ReturnValue, 'Valor Total Com 25% Desconto com erro!');
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTCompra.Suite);
end.

