unit TestUCalculadora;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, UCalculadora;

type
  // Test methods for class TCalculadora

  TestTCalculadora = class(TTestCase)
  strict private
    FCalculadora: TCalculadora;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestSomar;
    procedure TestSubtrair;
    procedure TestMultiplicar;
    procedure TestDividir;
  end;

implementation

procedure TestTCalculadora.SetUp;
begin
  FCalculadora := TCalculadora.Create;
end;

procedure TestTCalculadora.TearDown;
begin
  FCalculadora.Free;
  FCalculadora := nil;
end;

procedure TestTCalculadora.TestSomar;
var
  ReturnValue: Double;
  aNumero2: Double;
  aNumero1: Double;
begin
  aNumero1 := 1;
  aNumero2 := 2;

  ReturnValue := FCalculadora.Somar(aNumero1, aNumero2);
  CheckEquals(3, ReturnValue, 'Erro no método Somar');
end;

procedure TestTCalculadora.TestSubtrair;
var
  ReturnValue: Double;
  aNumero2: Double;
  aNumero1: Double;
begin
  aNumero1 := 1;
  aNumero2 := 2;

  ReturnValue := FCalculadora.Subtrair(aNumero1, aNumero2);

  CheckEquals(-1, ReturnValue, 'Erro no método Subtrair');
end;

procedure TestTCalculadora.TestMultiplicar;
var
  ReturnValue: Double;
  aNumero2: Double;
  aNumero1: Double;
begin
  aNumero1 := 1;
  aNumero2 := 2;

  ReturnValue := FCalculadora.Multiplicar(aNumero1, aNumero2);

  CheckEquals(2, ReturnValue, 'Erro no método Multiplicar');
end;

procedure TestTCalculadora.TestDividir;
var
  ReturnValue: Double;
  aNumero2: Double;
  aNumero1: Double;
begin
  aNumero1 := 1;
  aNumero2 := 2;

  ReturnValue := FCalculadora.Dividir(aNumero1, aNumero2);

  CheckEquals(0.5, ReturnValue, 'Erro no método Dividir');
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTCalculadora.Suite);
end.

